### ISSUE TITLE
Task: Explore the relationships between the performance and network statistics

### ISSUE THREAD

**Issue by skojaku** [skojaku/degree-corrected-link-prediction-benchmark#59]
# Task
The performance of the link predictors might have non-trivial dependencies on the network statistics (such as the degree heterogeneity, degree assortatitivity, diameter, # of triangles). 

Specific questions are:
- Are there the link prediction methods that perform consistently well or not? 
- Are there any common properties of the bad/good link prediction methods? 
- Can we get any insights into the design of the link prediction methods based on the common properties?

 

![image](https://github.com/skojaku/link-prediction/assets/18026375/16b3dfdd-2fa0-413b-bf58-0c2408978c42)

@rachithaiyappa @ocseckin @MunjungKim
Currently, I'm recomputing the graph neural networks due to some parameter changes for the community detection tasks. Once done, I'll send you the following two files, and it would be very helpful if you could explore to learn the relationships between performance and network statistics
- A csv file for the AUC-ROC scores for different methods 
- A csv file for the network statistics

Additionally, the raw network data are in ash right now, and will make it accessible by the time I will ask for the exploration.

**Comment by MunjungKim** [comment]
Hi! These are the plots of figure 1 in terms of different statistics! @skojaku @rachithaiyappa 


## log norm
![lognorm_sigma_uniform](https://github.com/user-attachments/assets/96a4d785-298a-4985-b8d2-4a6bc4daff27)
![lognorm_sigma_corrected](https://github.com/user-attachments/assets/6b3a503b-b8f6-4daa-b7cc-59e42e7881e7)

## local Transitivity
![localTransitivity_uniform](https://github.com/user-attachments/assets/ee56d192-548d-4342-b8a6-a8c75b3b3bba)
![localTransitivity_corrected](https://github.com/user-attachments/assets/0bd5b6dd-b58b-425c-837b-43f263635156)

## Global Transitivity
![globalTransitivity_uniform](https://github.com/user-attachments/assets/bdba0923-1c7a-4c19-b779-97b4e7e69e51)
![globalTransitivity_corrected (1)](https://github.com/user-attachments/assets/c2071890-84b2-4989-8da3-7f9f364813c6)

## Degree Heterogeniety
![degreeHeterogeneity_uniform](https://github.com/user-attachments/assets/cab06aaf-b932-4fda-bf91-f740ed48799b)
![degreeHeterogeneity_corrected](https://github.com/user-attachments/assets/34c38082-abb9-48e9-b0c2-2209cfbb9bc3)


## Degree Assortativity
![degreeAssortativity_uniform](https://github.com/user-attachments/assets/40d8a695-c6a1-45fc-91b1-0d8058018d44)
![degreeAssortativity_corrected](https://github.com/user-attachments/assets/64de7c2d-24d1-497a-bc01-9fcc3c76989c)

**Comment by skojaku** [comment]
Thanks! This is cool! Could you share them in pdf with me?

**Comment by MunjungKim** [comment]
Hi Sada! These are the pdf files! I added the x axis name as the corresponding statistics!


[degreeAssortativity_corrected.pdf](https://github.com/user-attachments/files/17880329/degreeAssortativity_corrected.pdf)
[degreeAssortativity_uniform.pdf](https://github.com/user-attachments/files/17880330/degreeAssortativity_uniform.pdf)
[globalTransitivity_corrected.pdf](https://github.com/user-attachments/files/17880331/globalTransitivity_corrected.pdf)
[globalTransitivity_uniform.pdf](https://github.com/user-attachments/files/17880332/globalTransitivity_uniform.pdf)
[localTransitivity_corrected.pdf](https://github.com/user-attachments/files/17880333/localTransitivity_corrected.pdf)
[localTransitivity_uniform.pdf](https://github.com/user-attachments/files/17880334/localTransitivity_uniform.pdf)
[lognorm_sigma_corrected.pdf](https://github.com/user-attachments/files/17880335/lognorm_sigma_corrected.pdf)
[lognorm_sigma_uniform.pdf](https://github.com/user-attachments/files/17880336/lognorm_sigma_uniform.pdf)
[maxDegree_corrected.pdf](https://github.com/user-attachments/files/17880337/maxDegree_corrected.pdf)
[maxDegree_uniform.pdf](https://github.com/user-attachments/files/17880338/maxDegree_uniform.pdf)

**Comment by MunjungKim** [comment]
Also these are the visualization of the pearsonr correlation between AUC ROC scores of PA and the network statistics, which you mentioned in the last meeting! 

![Correlation_PA_netowrkstats_v1](https://github.com/user-attachments/assets/8e7c68c5-01c5-489c-b60d-3d8e27f95fc8)
![Correlation_PA_netowrkstats_v2](https://github.com/user-attachments/assets/9626b453-4496-4c67-b724-7df8347c6ede)

**Comment by MunjungKim** [comment]
These are the methods that show better AUC-ROC scores than PA method for at least 30 networks data having degree Heterogeneity bigger than top 50 percentile

![Degree_Heterogeneity_localPathIndex_AUCROC](https://github.com/user-attachments/assets/f148c3d7-8aa6-45c5-a48f-647ce79a640c)
![Degree_Heterogeneity_dcSBM_AUCROC](https://github.com/user-attachments/assets/b601231b-4f72-4f78-a567-ec33459ecce2)
![Degree_Heterogeneity_localRandomWalk_AUCROC](https://github.com/user-attachments/assets/32f63898-8c3d-4c43-a73e-31d42626051f)
![Degree_Heterogeneity_SBM_AUCROC](https://github.com/user-attachments/assets/d44f89b8-e3e4-4aad-bd53-cef3aa8849e2)
![Degree_Heterogeneity_GAT_AUCROC](https://github.com/user-attachments/assets/85f419c3-ab17-42a6-9d25-3714e4910ed6)
![Degree_Heterogeneity_GraphSAGE_AUCROC](https://github.com/user-attachments/assets/3f6fa2c1-0e31-4719-9707-9a256e70ae05)

**Comment by MunjungKim** [comment]
These are the pearsonr correlation between degree Heterogeneity and AUC-ROC of the methods that show better performance than PA

![Correlation_AUC_ROC_Heterogeneity](https://github.com/user-attachments/assets/dc20bb33-164f-4608-b83d-86c85b222d68)
[Correlation_AUC_ROC_Heterogeneity.pdf](https://github.com/user-attachments/files/17881952/Correlation_AUC_ROC_Heterogeneity.pdf)

**Comment by skojaku** [comment]
thanks! @MunjungKim
